import { defineConfig } from 'vitest/config';
import preact from '@preact/preset-vite';

export default defineConfig({
  base: './',
  plugins: [preact()],
  worker: {
    format: 'es',
    rollupOptions: {
      // The wasm module is generated by the Rust build and absent in mock/CI.
      // Rollup resolves dynamic imports even in dead branches, so mark it external
      // when VITE_BACKEND=mock. It is never imported at runtime in that mode.
      external: process.env['VITE_BACKEND'] === 'mock' ? [/webspec_index_wasm/] : [],
    },
  },
  test: {
    environment: 'node',
  },
});
