import { defineConfig } from 'vitest/config';
import preact from '@preact/preset-vite';

export default defineConfig({
  base: './',
  plugins: [preact()],
  build: {
    // public/db holds the database export, which can be over a gigabyte during
    // development. The e2e build serves the fixture database from its own directory
    // instead of copying public/ into dist/.
    copyPublicDir: process.env['WEBSPEC_SKIP_PUBLIC_DB'] !== '1',
  },
  worker: {
    format: 'es',
    rollupOptions: {
      // The wasm module is generated by the Rust build and absent in mock/CI.
      // Rollup resolves dynamic imports even in dead branches, so mark it external
      // when VITE_BACKEND=mock. It is never imported at runtime in that mode.
      external: process.env['VITE_BACKEND'] === 'mock' ? [/webspec_index_wasm/] : [],
    },
  },
  test: {
    environment: 'node',
    exclude: ['e2e/**', '**/node_modules/**'],
  },
});
